/*
 * Copyright 2017-2018 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
 /***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_gint.h"
#include "fsl_spi.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define GINT0_PERIPHERAL GINT0
/* Definition of enabled pins of the PIO0 */
#define GINT0_PIO0_ENABLED_PINS_MASK 0x0UL
/* Definition of polarity pins of the PIO0 */
#define GINT0_PIO0_POLARITY_MASK 0x0UL
/* Definition of enabled pins of the PIO1 */
#define GINT0_PIO1_ENABLED_PINS_MASK 0x40000UL
/* Definition of polarity pins of the PIO1 */
#define GINT0_PIO1_POLARITY_MASK 0x0UL
/* Definition of the interrupt priority */
#define GINT0_GINT_IRQ_PRIORITY 0
/* BOARD_InitPeripherals defines for FLEXCOMM8 */
/* Definition of peripheral ID */
#define FLEXCOMM8_PERIPHERAL ((SPI_Type *)FLEXCOMM8)
/* Definition of the clock source frequency */
#define FLEXCOMM8_CLOCK_SOURCE 48000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const spi_master_config_t FLEXCOMM8_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* GINT callback function for the GINT0 component (init. function BOARD_InitPeripherals)*/
extern void pio1_18_gint_callback(void);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
