/*
 * Copyright 2017-2018 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
 /***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_ASW_DI 0x00u        /*!<@brief Analog switch is open (disabled) */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_FUNC6 0x06u         /*!<@brief Selects pin function 6 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name FC0_RXD_SDA_MOSI_DATA (number 92), U11[14]/U22[14]/FC0_USART_RXD
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO_WS (number 94), U11[13]/U22[13]/FC0_USART_TXD
  @{ */
/* @} */

/*! @name SWO (number 21), J9[1]/U18[12]/N4M_SWO
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_16_FUNC_ALT0 0x00u
/*!
 * @brief Input polarity.: Enabled. Input is function inverted. */
#define PIO0_16_INVERT_ENABLED 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_16_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO0_16_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_18_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_18_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_1_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_2_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_3_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_5_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_5_FUNC_ALT0 0x00u
/*!
 * @brief Input polarity.: Enabled. Input is function inverted. */
#define PIO1_5_INVERT_ENABLED 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_5_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO1_5_SLEW_STANDARD 0x00u

/*! @name PIO0_16 (number 14), J7[1]/J13[1]/JP4[1]/ARD_MIK_ADC0_8_N
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_QEI_phase_B_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_QEI_phase_B_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */
#define PINSFUNC_QEI_phase_B_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_QEI_phase_B_PIN 16U                   /*!<@brief PORT pin number */
#define PINSFUNC_QEI_phase_B_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO1_5 (number 31), J8[1]/J9[18]/ARD_MIK_P1_5
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_QEI_phase_A_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_QEI_phase_A_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */
#define PINSFUNC_QEI_phase_A_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_QEI_phase_A_PIN 5U                   /*!<@brief PORT pin number */
#define PINSFUNC_QEI_phase_A_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO1_18 (number 64), SW1/J8[2]/J12[15]/MIK_EXP_BTN_WK
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_QEI_Knob_detect_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_QEI_Knob_detect_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */
#define PINSFUNC_QEI_Knob_detect_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_QEI_Knob_detect_PIN 18U                   /*!<@brief PORT pin number */
#define PINSFUNC_QEI_Knob_detect_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name HS_SPI_SCK (number 61), J7[4]/J9[10]/ARD_MIK_HSSPI_SCK
  @{ */
/* @} */

/*! @name HS_SPI_MISO (number 62), J7[5]/J9[12]/ARD_MIK_HSSPI_MISO
  @{ */
/* @} */

/*! @name HS_SPI_MOSI (number 60), J7[6]/J9[14]/ARD_MIK_HSSPI_MOSI
  @{ */
/* @} */

/*! @name PIO1_1 (number 59), J7[3]/J9[16]/ARD_MIK_HSSPI_SSEL1
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_QEI_CS_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_QEI_CS_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define PINSFUNC_QEI_CS_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_QEI_CS_PIN 1U                   /*!<@brief PORT pin number */
#define PINSFUNC_QEI_CS_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PinsFunc_QEI(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
